package com.ai.amc.core.dao.mapper;

import java.util.List;

import com.ai.amc.core.po.Trends;
import com.ai.amc.core.po.TrendsKey;

public interface TrendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trends
     *
     * @mbggenerated
     */
   
    List<Trends> selectByPrimaryKey(TrendsKey key);

   
}