package com.ai.amc.core.po;

import java.io.Serializable;
import java.text.SimpleDateFormat;

public class Trends_uint implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


    private Integer num;


    private Long valueMin;


    private Long valueAvg;

    
    private Long valueMax;

    private Long itemid;

    private Integer clock;
    private String newclock;
    
    public Long getItemid() {
		return itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

	public Integer getClock() {
		return clock;
	}

	public void setClock(Integer clock) {
		this.clock = clock;
	}

	public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends_uint.num
     *
     * @param num the value for trends_uint.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends_uint.value_min
     *
     * @return the value of trends_uint.value_min
     *
     * @mbggenerated
     */
    public Long getValueMin() {
        return valueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends_uint.value_min
     *
     * @param valueMin the value for trends_uint.value_min
     *
     * @mbggenerated
     */
    public void setValueMin(Long valueMin) {
        this.valueMin = valueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends_uint.value_avg
     *
     * @return the value of trends_uint.value_avg
     *
     * @mbggenerated
     */
    public Long getValueAvg() {
        return valueAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends_uint.value_avg
     *
     * @param valueAvg the value for trends_uint.value_avg
     *
     * @mbggenerated
     */
    public void setValueAvg(Long valueAvg) {
        this.valueAvg = valueAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends_uint.value_max
     *
     * @return the value of trends_uint.value_max
     *
     * @mbggenerated
     */
    public Long getValueMax() {
        return valueMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends_uint.value_max
     *
     * @param valueMax the value for trends_uint.value_max
     *
     * @mbggenerated
     */
    public void setValueMax(Long valueMax) {
        this.valueMax = valueMax;
    }

	public String getNewclock() {
		Long oldc =Long.valueOf(this.getClock());
		SimpleDateFormat bartDateFormat =  new SimpleDateFormat("YYYY/MM/dd HH:mm");
		return bartDateFormat.format(oldc*1000);
	}

	public void setNewclock(String newclock) {
		this.newclock = newclock;
	}
}