package com.ai.amc.core.po;

import java.io.Serializable;

public class TrendsKey implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trends.itemid
     *
     * @mbggenerated
     */
	private static final long serialVersionUID = 1L;
    private Long itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trends.clock
     *
     * @mbggenerated
     */
    private Integer clock_begin;
    private Integer clock_end;
    private Integer interval;

    public Integer getClock_begin() {
		return clock_begin;
	}

	public void setClock_begin(Integer clock_begin) {
		this.clock_begin = clock_begin;
	}

	public Integer getClock_end() {
		return clock_end;
	}

	public void setClock_end(Integer clock_end) {
		this.clock_end = clock_end;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.itemid
     *
     * @return the value of trends.itemid
     *
     * @mbggenerated
     */
    public Long getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends.itemid
     *
     * @param itemid the value for trends.itemid
     *
     * @mbggenerated
     */
    public void setItemid(Long itemid) {
        this.itemid = itemid;
    }

	public Integer getInterval() {
		return interval;
	}

	public void setInterval(Integer interval) {
		this.interval = interval;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.clock
     *
     * @return the value of trends.clock
     *
     * @mbggenerated
     */
   
}