package com.ai.amc.core.po;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Trends implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trends.num
     *
     * @mbggenerated
     */
	private static final long serialVersionUID = 1L;
	private Long itemid;
	 
    private Integer num;
   
	private Integer clock;

    private Double valueMin;

    private Double valueAvg;

    private Double valueMax;
    
    private String newclock;
    
    public String getNewclock() {
    	Long oldc =Long.valueOf(this.getClock());
		SimpleDateFormat bartDateFormat =  new SimpleDateFormat("YYYY/MM/dd HH:mm");
		return bartDateFormat.format(oldc*1000);
	}
	public void setNewclock(String newclock) {
		this.newclock = newclock;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.num
     *
     * @return the value of trends.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends.num
     *
     * @param num the value for trends.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
    
    
    public Long getItemid() {
		return itemid;
	}

	public void setItemid(Long itemid) {
		this.itemid = itemid;
	}

	public Integer getClock() {
		return clock;
	}

	public void setClock(Integer clock) {
		this.clock = clock;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.value_min
     *
     * @return the value of trends.value_min
     *
     * @mbggenerated
     */
    public Double getValueMin() {
        return valueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends.value_min
     *
     * @param valueMin the value for trends.value_min
     *
     * @mbggenerated
     */
    public void setValueMin(Double valueMin) {
        this.valueMin = valueMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.value_avg
     *
     * @return the value of trends.value_avg
     *
     * @mbggenerated
     */
    public Double getValueAvg() {
        return valueAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends.value_avg
     *
     * @param valueAvg the value for trends.value_avg
     *
     * @mbggenerated
     */
    public void setValueAvg(Double valueAvg) {
        this.valueAvg = valueAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trends.value_max
     *
     * @return the value of trends.value_max
     *
     * @mbggenerated
     */
    public Double getValueMax() {
        return valueMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trends.value_max
     *
     * @param valueMax the value for trends.value_max
     *
     * @mbggenerated
     */
    public void setValueMax(Double valueMax) {
        this.valueMax = valueMax;
    }
}